---
title: "Lab 6"
output: html_document
---
```{r , message=FALSE}
library(tidyverse)
library(maps)
library(mapdata)
library(lubridate)
library(viridis)
library(wesanderson)
library(RColorBrewer)
library(plotly)
```


# Building Maps

```{r, echo=FALSE, message=FALSE, warning=FALSE}
daily_report<- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/04-02-2020.csv")) %>% 
  rename(Long = "Long_")

ggplot(daily_report, aes(x=Long, y=Lat, size= Confirmed/1000))+
  borders(database = "world", colour = NA, fill = "grey90")+
  theme_bw()+
  geom_point(shape=21, colour= "purple", fill= "purple", alpha=0.5)+
  labs(title= "World COVID-19 Confirmed Cases", x="", y="", size= "Cases (X1000)")+
  theme(legend.position = "right")+
  coord_fixed(ratio=1.5)
```

Zoom in on US 48 states


```{r, echo=FALSE, message=FALSE, warning=FALSE}
daily_report<- daily_report %>% 
  filter(Country_Region=="US") %>% 
  filter(!Province_State %in% c("Alaska","Hawaii", "American Samoa",
                  "Puerto Rico","Northern Mariana Islands", 
                  "Virgin Islands", "Recovered", "Guam", "Grand Princess",
                  "District of Columbia", "Diamond Princess")) %>% 
  filter(Lat>0) 
  
  ggplot( daily_report, aes(x=Long, y=Lat, size= Confirmed/1000))+
  borders(database = "state", colour = "black", fill = "grey90")+
  theme_bw()+
  geom_point(shape=21, colour= "purple", fill= "purple", alpha=0.5)+
  labs(title= "COVID-19 Confirmed Cases In US", x="", y="", size= "Cases (X1000)")+
  theme(legend.position = "right")+
  coord_fixed(ratio=1.5)
```
```{r, echo=FALSE, message=FALSE, warning=FALSE}
mybreaks <- c(1, 100, 1000, 10000, 10000)
ggplot(daily_report, aes(x=Long, y= Lat, size= Confirmed))+
  borders("state", colour= "white", fill="grey90")+
  geom_point(aes(color=Confirmed), stroke=F, alpha=0.7)+
  scale_size_continuous(name="Cases", trans="log", range=c(1,7), 
                        breaks=mybreaks, labels = c("1-99",
                        "100-999", "1,000-9,999", "10,000-99,999", "50,000+"))+
  scale_color_viridis(option = "virids", name= "Cases", trans="log", 
                        breaks=mybreaks, labels = c("1-99",
                        "100-999", "1,000-9,999", "10,000-99,999", "50,000+"))+
  theme_void()+
  guides(colour= guide_legend())+
  labs(title= "Anisa Dhana's lagout for COVID-19 Confirmed Cases in the US"
)+
   theme(
      legend.position = "bottom",
      text = element_text(color = "#22211d"),
      plot.background = element_rect(fill = "#ffffff", color = NA), 
      panel.background = element_rect(fill = "#ffffff", color = NA), 
      legend.background = element_rect(fill = "#ffffff", color = NA)
    ) +
    coord_fixed(ratio=1.5)
  
```
# Mapping Data To Shapes

```{r, echo=FALSE, message=FALSE, warning=FALSE}
daily_report <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/04-02-2020.csv")) %>% 
  rename(Long="Long_") %>% 
  filter(Country_Region == "US") %>% 
  group_by(Province_State) %>% 
  summarise(Confirmed= sum(Confirmed)) %>% 
  mutate(Province_State= tolower(Province_State))

us <- map_data("state")
state_join <- left_join(x= us, y= daily_report, by=c("region"="Province_State"))
```


# Using R color plates

## Wes Anderson
```{r, echo=FALSE, message=FALSE, warning=FALSE}
ggplot(data=us, mapping=aes(x=long, y=lat, group= group))+
  coord_fixed(ratio = 1.3)+
  geom_polygon(data= state_join, aes(fill=Confirmed), color="black")+
  scale_fill_gradientn(colours= wes_palette("Zissou1", 100, type = "continuous"),
                         trans = "log10")+
  labs(title= "COVID-19 Confirmed Cases in the US")
  
```

## RColorBrewer

```{r, echo=FALSE, message=FALSE, warning=FALSE}
report_03_27_2020 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/04-02-2020.csv")) %>% 
  rename(Long = "Long_") %>% 
  unite(Key, Admin2, Province_State, sep = ".") %>% 
  group_by(Key) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  mutate(Key = tolower(Key))

us<- map_data("state")
counties <- map_data("county") %>% 
  unite(col= Key, subregion, region, sep= ".", remove=FALSE)

state_join <- left_join(x=counties, y= report_03_27_2020, by= c("Key"))

ggplot(data=us, mapping = aes(x=long, y=lat, group=group))+
  coord_fixed(ratio= 1.3)+
  borders("state", colour = "black")+
  geom_polygon(data= state_join, aes(fill=Confirmed))+
  scale_fill_gradientn(colors = brewer.pal(n=5, name = "PuRd"),
          breaks = c(1, 10, 100, 1000, 10000, 100000),
          trans = "log10", na.value = "White")+
  ggtitle("Number of Confirmed Cases by US County")+
  theme_bw()
  

```
## Visualizing Massachusetts Data

```{r, echo=FALSE, message=FALSE, warning=FALSE}
daily_report <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/04-02-2020.csv")) %>% 
  rename(Long = "Long_") %>% 
  filter(Province_State == "Massachusetts") %>% 
  group_by(Admin2) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  mutate(Admin2 = tolower(Admin2))
us <- map_data("state")
ma_us <- subset(us, region == "massachusetts")
counties <- map_data("county")
ma_county <- subset(counties, region == "massachusetts")
state_join <- left_join(ma_county, daily_report, by = c("subregion" = "Admin2")) 
# plot state map
ggplot(data = ma_county, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
# Add data layer
  geom_polygon(data = state_join, aes(fill = Confirmed), color = "white") +
    scale_fill_gradientn(colors = brewer.pal(n = 5, name = "BuGn"),
                         trans = "log10") +
  labs(title = "COVID-19 Confirmed Cases in Massachusetts'")
```

## Interactive graphs


```{r, echo=FALSE, message=FALSE, warning=FALSE}
ggplot(data=ma_county, mapping = aes(x=long, y= lat, group= group))+
  coord_fixed(ratio = 1.3)+
  geom_polygon(data=state_join, aes(fill=Confirmed), color="black" )+
  scale_fill_gradientn(colours = wes_palette("Zissou1", 100, type = "continuous"))+
  ggtitle("COVID-19 Cases in MA")+
  labs(x=NULL, y= NULL)+
  theme(panel.border = element_blank()) +
  theme(panel.background = element_blank()) +
  theme(axis.ticks = element_blank()) +
  theme(axis.text = element_blank())
  
```

# **Exercise**


1. For the above graph “World COVID-19 Confirmed case” summarize the counts for each Country on the graph and update the graph to 9/26/2020. You may need to adjust the size of the points
